# Long-term Changes in Renal Function after Living Kidney Donation

### [Statistical analysis performed by David M. Vock, Ph.D.](https://sites.google.com/site/dmvock/)

### [University of Minnesota Division of Biostatistics](http://sph.umn.edu/biostatistics/)


---

The files in this repository comprise the source code for reproducing the work in the manuscript **Long-term Changes in Renal Function after Living Kidney Donation**. Code to implement the longitudinal models and clean the data are provided in the SAS programming language. Graphics and summary tables are given in the R programming language. Due to privacy concerns, the analytic dataset cannot be made publicly available. 

### File Organization

The file `readin_final.sas` takes the standard donor dataset and creates an analytic dataset (one observation per subject) with white subjects donating between January 1, 1990 and December 31, 2014 with at least one creatinine measurement 6 weeks after donation. `demographic_table_final.R` creates Table 1, a comparison of demographic and clinical characteristics between donor with and without a first degree family history of end stage renal disease. The file `longitudinal_models_final.sas` fits the linear mixed effects model of the estimated glomerular filtration trajectory after 6 weeks post-donation. Graphical summaries of this model (Figure 1 in the manuscript) are created in `longitudinal_models_trajectory_finl.R`. The files above also contain code to repeat the analysis using all white donors donating before December 31, 2014.     

---


